### ISSUE TITLE
Implement the design of popit.poplus.org

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/popit.poplus.org#1]
![popit-poplus-home](https://cloud.githubusercontent.com/assets/2292925/2733459/d480618e-c646-11e3-85ae-1f38feabc93b.png)
![poplus-about-page](https://cloud.githubusercontent.com/assets/2292925/2733460/d4832db0-c646-11e3-9896-994edf8fcfb9.png)

**Comment by chrismytton** [comment]
@wrightmartin Can this ticket be closed now?

**Comment by wrightmartin** [comment]
Yep, thanks @hecticjeff
