### ISSUE TITLE
Only have one "About" page

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popit.poplus.org#10]
There are effective two "About" pages at the minute. The link on the front page goes to what is essentially the main Documentation page, but which acts as a general (though brief) introduction. There is also /about (although it's not as obvious that you can click on the section header to get there), but that text is much older, and needs a lot more work.

**Comment by chrismytton** [comment]
The documentation entry point now doesn't have much in the way of "about" details and the [about page](http://popit.poplus.org/about/) has been updated with new copy.
