### ISSUE TITLE
"Get Started"

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popit.poplus.org#11]
The "Get Started" link on the homepage currently goes to the github repo. I'm assuming this will go to http://popit.mysociety.org/ ?

**Comment by wrightmartin** [comment]
@tmtmtmtm that depends - Get started for a developer looking to roll their own might be github, but for a non-technical user yes - I guess it should go to http://popit.mysociety.org/ 

I think those buttons that appear on the homepage probably need a rethink - any further thoughts?

**Comment by tmtmtmtm** [comment]
If the first big link is to github, it'll put off non technical people, whereas developers should be OK with the slightly less prominent link at the top right. 

But, yes, I suspect we probably want slightly different paths here anyway: the main entry point should be to a What does PopIt Do? / Why would I use it? introduction, and then secondarily to How do I use it? (which can in turn split on "Play with a new instance on popit.mysociety" vs tech "How do I use the API"-style documentation)

**Comment by wrightmartin** [comment]
Thanks Tony, I agree. In the short term I'll change the button, I think we're due to do a content review on this site with myf shortly, lets pick it up then
