### ISSUE TITLE
Configure DNS for popit.poplus.org

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/popit.poplus.org#2]

**Comment by wrightmartin** [comment]
We'll need someone at FCI to do this

**Comment by chrismytton** [comment]
Done

```
$ dig popit.poplus.org +nostats +nocomments +nocmd @8.8.8.8

; <<>> DiG 9.8.3-P1 <<>> popit.poplus.org +nostats +nocomments +nocmd @8.8.8.8
;; global options: +cmd
;popit.poplus.org.              IN      A
popit.poplus.org.       289     IN      CNAME   mysociety.github.io.
mysociety.github.io.    2115    IN      CNAME   github.map.fastly.net.
github.map.fastly.net.  13      IN      A       185.31.18.133
```

**Comment by TomSteinberg** [comment]
Excellent. It occurs to me that before this is of any value to anyone, though, it now needs to be linked to from the poplus.org homepage. @tmtmtmtm ?

**Comment by tmtmtmtm** [comment]
It's still a little too full of placeholder text like "Privacy text goes here" for my liking, though we could certainly replace the link on http://poplus.org/catalogue.html fairly quickly. 

I'm assuming the goal is to quite quickly have equivalent pages like this for all the existing Components? If so, then replacing the banner for PoplusCon on the home page with a banner-like set of links to each of those is probably a good approach.

**Comment by chrismytton** [comment]
> I'm assuming the goal is to quite quickly have equivalent pages like this for all the existing Components? 

Yep, the DNS for the following sites has been sorted:
- http://popit.poplus.org/
- http://sayit.poplus.org/
- http://mapit.poplus.org/
- http://writeit.poplus.org/
