### ISSUE TITLE
ethering data

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popit.poplus.org#7]
http://popit.poplus.org/about/privacy.html says:

"By uploading and ethering data to PopIt". This seems like it's meant to say "tethering", but that also seems odd.

**Comment by chrismytton** [comment]
Perhaps it was meant to be "entering", which would make sense in this context?

**Comment by tmtmtmtm** [comment]
That could make sense too, although in that case it should really be "uploading or entering" rather than "and".
