### ISSUE TITLE
Self-hosting

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popit.poplus.org#8]
self-hosting.html suggests: "You might want your own site if your users are not near the UK (where our servers are based). Or you might want to access the database directly, rather than using the API."

I'm not sure that suggesting people work directly with the database (without lots of warnings) is a good idea. The preferred path is surely still to use the API on a local install, rather than completely breaking things open?

**Comment by chrismytton** [comment]
The copy about accessing the database directly has been removed now.
